// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'adapters/objectbox_adapter.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 789651532059846914),
    name: 'RecordEntity',
    lastPropertyId: const obx_int.IdUid(7, 7328733773881864063),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2989605087455382297),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4852490533480504535),
        name: 'recordId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 2551551332757528746),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4819381150993781041),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3075881836950725664),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7910448571004698468),
        name: 'age',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8046570575911540391),
        name: 'score',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7328733773881864063),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 789651532059846914),
    lastIndexId: const obx_int.IdUid(1, 2551551332757528746),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RecordEntity: obx_int.EntityDefinition<RecordEntity>(
      model: _entities[0],
      toOneRelations: (RecordEntity object) => [],
      toManyRelations: (RecordEntity object) => {},
      getId: (RecordEntity object) => object.obxId,
      setId: (RecordEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (RecordEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        fbb.startTable(8);
        fbb.addInt64(0, object.obxId);
        fbb.addInt64(1, object.recordId);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addInt64(4, object.age);
        fbb.addFloat64(5, object.score);
        fbb.addInt64(6, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final recordIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final ageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final scoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
        );
        final object = RecordEntity(
          recordId: recordIdParam,
          name: nameParam,
          email: emailParam,
          age: ageParam,
          score: scoreParam,
          createdAt: createdAtParam,
        )..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RecordEntity] entity fields to define ObjectBox queries.
class RecordEntity_ {
  /// See [RecordEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<RecordEntity>(
    _entities[0].properties[0],
  );

  /// See [RecordEntity.recordId].
  static final recordId = obx.QueryIntegerProperty<RecordEntity>(
    _entities[0].properties[1],
  );

  /// See [RecordEntity.name].
  static final name = obx.QueryStringProperty<RecordEntity>(
    _entities[0].properties[2],
  );

  /// See [RecordEntity.email].
  static final email = obx.QueryStringProperty<RecordEntity>(
    _entities[0].properties[3],
  );

  /// See [RecordEntity.age].
  static final age = obx.QueryIntegerProperty<RecordEntity>(
    _entities[0].properties[4],
  );

  /// See [RecordEntity.score].
  static final score = obx.QueryDoubleProperty<RecordEntity>(
    _entities[0].properties[5],
  );

  /// See [RecordEntity.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<RecordEntity>(
    _entities[0].properties[6],
  );
}
