/// Schema metadata for a NodeDB collection/node/edge.
///
/// Generated by `nodedb_generator` for each annotated class.
class NodeDbSchema {
  final String name;
  final String schema;
  final bool singleton;
  final String type;
  final List<SchemaField> fields;
  final bool trimmable;
  final String? trimPolicy;
  final bool neverTrim;
  final bool backup;

  const NodeDbSchema({
    required this.name,
    required this.schema,
    required this.singleton,
    required this.type,
    required this.fields,
    this.trimmable = false,
    this.trimPolicy,
    this.neverTrim = false,
    this.backup = true,
  });
}

/// Field metadata within a schema.
class SchemaField {
  final String name;
  final String type;
  final bool indexed;
  final bool unique;

  const SchemaField(
    this.name,
    this.type, {
    this.indexed = false,
    this.unique = false,
  });
}
