name: nodedb_generator
description: Code generator for NodeDB annotations — produces schemas, typed query builders, and DAOs
version: 0.0.1
publish_to: none
homepage: https://github.com/virnavi/nodedb
repository: https://github.com/virnavi/nodedb
issue_tracker: https://github.com/virnavi/nodedb/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  nodedb:
    git:
      url: https://github.com/virnavi/nodedb
      ref: "0.0.1"
      path: packages/nodedb
  build: ^2.4.0
  source_gen: ^1.5.0
  analyzer: '>=6.0.0 <7.0.0'
  code_builder: ^4.10.0
  dart_style: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  test: ^1.24.0
  lints: ^4.0.0
